CREATE DATABASE PUTAQUEOPARIU

USE PUTAQUEOPARIU

CREATE TABLE FUNCIONARIOS
(
    FUNCIONARIOCOD INT PRIMARY KEY,
    FUNCIONARIONOME VARCHAR(50) NOT NULL,
)

INSERT FUNCIONARIOS (FUNCIONARIOCOD, FUNCIONARIONOME) VALUES(1, 'JOAO')
CREATE TABLE DEPENDENTES
(
    DEPENDENTECOD INT PRIMARY KEY,
    DEPENDENTENOME VARCHAR(50) NOT NULL,
    FUNCIONARIOCOD INT 
    CONSTRAINT FK_FUNCIONARIOS FOREIGN KEY (FUNCIONARIOCOD)
    REFERENCES FUNCIONARIOS(FUNCIONARIOCOD)
)

INSERT DEPENDENTES (DEPENDENTECOD, DEPENDENTENOME, FUNCIONARIOCOD) 
VALUES(1, 'MARIA', 1)

SELECT * FROM FUNCIONARIOS
SELECT * FROM DEPENDENTES
DELETE FROM FUNCIONARIOS
WHERE FUNCIONARIOCOD = 1
    

